spring:
  cloud:
    gateway:
      routes:
        - id: domain-user
          uri: lb://domain-user
          predicates:
           - Path=/api/user/**
          filters:
           - StripPrefix=2
        - id: domain-example
          uri: lb://domain-example
          predicates:
           - Path=/api/example/**
          filters:
           - StripPrefix=2
        - id: platform-security
          uri: lb://platform-security
          predicates:
           - Path=/api/security/**
          filters:
           - StripPrefix=2